In [698]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [726]:
import pandas as pd

In [728]:
df = pd.read_csv(r"C:\Users\vv\OneDrive\Desktop\PYTHON\DEEP LEARNING\ai_jobs_market_2025_2026.csv")
df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,APIs|Planning Systems|Python|Cloud|SQL|Leadership,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,Python|Documentation|LLM APIs|Prompt Design|NL...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,Vector DBs|Python|Prompt Engineering|Fine-tuni...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)
3,AIJOB0004,Data Engineer (AI),Data Engineering,Senior (6-9 yrs),3,Bachelor's,161000.0,130000,220000,Singapore,Singapore,Fully Remote,SME (51-500),Technology,Feature Stores|Spark|ETL|Airflow|dbt|SQL|Pytho...,12.0,88,6.7,9.5,2026,3,1,1,0,Upper-Mid ($150-200k)
4,AIJOB0005,AI Product Manager,Product,Lead (10+ yrs),5,Bootcamp/Self-taught,283000.0,140000,260000,Los Angeles,USA,Fully Remote,Enterprise (5000+),Automotive,Data Analysis|Stakeholder Mgmt|Agile|Cloud|Pro...,9.4,85,17.3,8.9,2026,1,1,1,0,Senior ($200-300k)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,AIJOB1496,Multimodal AI Engineer,AI Engineering,Lead (10+ yrs),8,Master's,262000.0,160000,300000,Toronto,Canada,Hybrid,SME (51-500),Retail,Python|Vision-Language Models|Fine-tuning|PyTo...,8.8,90,23.6,7.5,2026,1,1,1,0,Senior ($200-300k)
1496,AIJOB1497,NLP Engineer,AI Engineering,Senior (6-9 yrs),9,Bootcamp/Self-taught,163000.0,145000,290000,Berlin,Germany,On-site,Mid-size (501-5000),Manufacturing,Transformers|Text Processing|LLMs|Hugging Face...,6.7,91,66.5,7.8,2025,3,1,0,0,Upper-Mid ($150-200k)
1497,AIJOB1498,AI Compliance Manager,Governance,Mid (3-5 yrs),10,Master's,127000.0,100000,200000,Zurich,Switzerland,Hybrid,SME (51-500),Manufacturing,Documentation|Risk Management|Legal Knowledge|...,10.9,68,15.3,8.3,2026,3,0,1,0,Mid ($100-150k)
1498,AIJOB1499,NLP Engineer,AI Engineering,Lead (10+ yrs),4,Bachelor's,145000.0,145000,290000,Bangalore,India,Hybrid,Enterprise (5000+),Media,LLMs|Hugging Face|Python|Transformers|BERT|Tex...,8.5,91,78.8,7.4,2025,5,1,1,0,Mid ($100-150k)
1499,AIJOB1500,AI Security Engineer,Security,Lead (10+ yrs),5,Master's,229000.0,140000,260000,Berlin,Germany,Hybrid,Enterprise (5000+),Technology,Cybersecurity|ML Security|Red Teaming|Python|R...,12.2,80,9.0,8.6,2025,6,1,1,0,Senior ($200-300k)

In [729]:
# pd.reset_option('display.max_columns', None)

In [730]:
df['job_title'].unique()

array(['AI Agent Developer', 'Prompt Engineer', 'LLM Engineer',
       'Data Engineer (AI)', 'AI Product Manager', 'AI Security Engineer',
       'Senior ML Engineer', 'NLP Engineer', 'AI Solutions Architect',
       'ML Engineer', 'Generative AI Engineer', 'Deep Learning Engineer',
       'Multimodal AI Engineer', 'MLOps Engineer', 'AI Business Analyst',
       'RAG Engineer', 'Robotics Engineer (AI)', 'Senior Data Scientist',
       'AI Ethics Officer', 'AI Infrastructure Eng', 'AI Engineer',
       'Data Scientist', 'Computer Vision Engineer',
       'AI Compliance Manager', 'AI Research Scientist'], dtype=object)

In [731]:
df['job_title'].nunique()

25

In [732]:
from sklearn.preprocessing import LabelEncoder

le_job = LabelEncoder()
s = le_job.fit_transform(df["job_title"])

In [733]:
print(le_job.classes_)

['AI Agent Developer' 'AI Business Analyst' 'AI Compliance Manager'
 'AI Engineer' 'AI Ethics Officer' 'AI Infrastructure Eng'
 'AI Product Manager' 'AI Research Scientist' 'AI Security Engineer'
 'AI Solutions Architect' 'Computer Vision Engineer' 'Data Engineer (AI)'
 'Data Scientist' 'Deep Learning Engineer' 'Generative AI Engineer'
 'LLM Engineer' 'ML Engineer' 'MLOps Engineer' 'Multimodal AI Engineer'
 'NLP Engineer' 'Prompt Engineer' 'RAG Engineer' 'Robotics Engineer (AI)'
 'Senior Data Scientist' 'Senior ML Engineer']

In [734]:
le_dict = {}

categorical_cols = ['job_title',
    'job_category','experience_level','education_required',
    'salary_tier','city','job_id','country',
    'company_size','industry','required_skills','remote_work'
]

for col in categorical_cols:
    le_dict[col] = LabelEncoder()
    df[col] = le_dict[col].fit_transform(df[col])

In [735]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 1500 non-null   int64
 1   job_title              1500 non-null   int64
 2   job_category           1500 non-null   int64
 3   experience_level       1500 non-null   int64
 4   years_of_experience    1500 non-null   int64
 5   education_required     1500 non-null   int64
 6   annual_salary_usd      1500 non-null   float64
 7   salary_min_usd         1500 non-null   int64
 8   salary_max_usd         1500 non-null   int64
 9   city                   1500 non-null   int64
 10  country                1500 non-null   int64
 11  remote_work            1500 non-null   int64
 12  company_size           1500 non-null   int64
 13  industry               1500 non-null   int64
 14  required_skills        1500 non-null   int64
 15  ai_salary_premium_pct  1500 non-null   float64
 16  demand_score           1500 non-null   int64
 17  demand_growth_yoy_pct  1500 non-null   float64
 18  benefits_score_10      1500 non-null   float64
 19  posting_year           1500 non-null   int64
 20  posting_month          1500 non-null   int64
 21  is_senior              1500 non-null   int64
 22  is_remote_friendly     1500 non-null   int64
 23  is_llm_role            1500 non-null   int64
 24  salary_tier            1500 non-null   int64
dtypes: float64(4), int64(21)
memory usage: 293.1 KB

In [736]:
df

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,0,0,0,3,7,3,239000.0,155000,290000,5,13,2,4,4,32,13.1,96,16.9,6.8,2026,3,1,0,1,3
1,1,20,0,3,2,1,166000.0,90000,200000,8,12,1,1,4,1043,5.4,82,11.6,6.2,2026,1,1,1,1,4
2,2,15,0,3,4,0,360000.0,160000,300000,14,13,0,0,4,1480,9.1,98,42.7,7.7,2026,1,1,1,1,0
3,3,11,3,3,3,1,161000.0,130000,220000,15,9,0,3,11,478,12.0,88,6.7,9.5,2026,3,1,1,0,4
4,4,6,8,1,5,2,283000.0,140000,260000,9,13,0,1,0,291,9.4,85,17.3,8.9,2026,1,1,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1495,18,0,1,8,3,262000.0,160000,300000,18,1,1,3,10,1184,8.8,90,23.6,7.5,2026,1,1,1,0,3
1496,1496,19,0,3,9,2,163000.0,145000,290000,4,4,2,2,7,1464,6.7,91,66.5,7.8,2025,3,1,0,0,4
1497,1497,2,5,2,10,3,127000.0,100000,200000,19,10,1,3,7,421,10.9,68,15.3,8.3,2026,3,0,1,0,2
1498,1498,19,0,1,4,1,145000.0,145000,290000,2,6,1,1,8,631,8.5,91,78.8,7.4,2025,5,1,1,0,2
1499,1499,8,11,1,5,3,229000.0,140000,260000,4,4,1,1,11,265,12.2,80,9.0,8.6,2025,6,1,1,0,3

In [737]:
x = df.drop("job_title", axis=1)
y = df.iloc[0:, 1:2]

In [738]:
x

,job_id,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,0,0,3,7,3,239000.0,155000,290000,5,13,2,4,4,32,13.1,96,16.9,6.8,2026,3,1,0,1,3
1,1,0,3,2,1,166000.0,90000,200000,8,12,1,1,4,1043,5.4,82,11.6,6.2,2026,1,1,1,1,4
2,2,0,3,4,0,360000.0,160000,300000,14,13,0,0,4,1480,9.1,98,42.7,7.7,2026,1,1,1,1,0
3,3,3,3,3,1,161000.0,130000,220000,15,9,0,3,11,478,12.0,88,6.7,9.5,2026,3,1,1,0,4
4,4,8,1,5,2,283000.0,140000,260000,9,13,0,1,0,291,9.4,85,17.3,8.9,2026,1,1,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1495,0,1,8,3,262000.0,160000,300000,18,1,1,3,10,1184,8.8,90,23.6,7.5,2026,1,1,1,0,3
1496,1496,0,3,9,2,163000.0,145000,290000,4,4,2,2,7,1464,6.7,91,66.5,7.8,2025,3,1,0,0,4
1497,1497,5,2,10,3,127000.0,100000,200000,19,10,1,3,7,421,10.9,68,15.3,8.3,2026,3,0,1,0,2
1498,1498,0,1,4,1,145000.0,145000,290000,2,6,1,1,8,631,8.5,91,78.8,7.4,2025,5,1,1,0,2
1499,1499,11,1,5,3,229000.0,140000,260000,4,4,1,1,11,265,12.2,80,9.0,8.6,2025,6,1,1,0,3

In [739]:
x.shape

(1500, 24)

In [740]:
y

      job_title
0             0
1            20
2            15
3            11
4             6
...         ...
1495         18
1496         19
1497          2
1498         19
1499          8

[1500 rows x 1 columns]

In [741]:
# Train-Test Split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=42)

In [742]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

In [743]:
# Build ANN Model and HIDDEN layers
# Index 0 (train_sc.shape[0]): Represents the total number of rows (sample size).
# Index 1 (train_sc.shape[1]): Represents the total number of columns (features or variables).

classifier = Sequential()

classifier.add(Dense(units=128, activation='relu',input_shape=(x_train_sc.shape[1],)))
classifier.add(Dropout(0.2))

C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [744]:
classifier.add(Dense(units=64, activation='relu'))
classifier.add(Dropout(0.2))

In [745]:
# classifier.add(Dense(units=32, activation='relu'))

In [746]:
classifier.add(Dense(units=25,activation='softmax'))

In [747]:
# Compile Model

classifier.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [748]:
# Train Model

classifier.fit(x_train_sc, y_train, batch_size=32, epochs=100)

Epoch 1/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.1133 - loss: 3.1249
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2450 - loss: 2.6978
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3850 - loss: 2.1625
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5225 - loss: 1.6379
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5967 - loss: 1.3039
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6617 - loss: 1.0814
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7000 - loss: 0.9121
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7350 - loss: 0.8014
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7625 - loss: 0.7025
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7892 - loss: 0.6293
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8133 - loss: 0.5753
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8183 - loss: 0.5289
Epoch 13/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8433 - loss: 0.4786
Epoch 14/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8475 - loss: 0.4539
Epoch 15/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8642 - loss: 0.4039
Epoch 16/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8642 - loss: 0.3925
Epoch 17/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8750 - loss: 0.3567
Epoch 18/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8875 - loss: 0.3318
Epoch 19/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8933 - loss: 0.3133
Epoch 20/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8967 - loss: 0.3062
Epoch 21/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9175 - loss: 0.2684
Epoch 22/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9167 - loss: 0.2629
Epoch 23/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9217 - loss: 0.2502
Epoch 24/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9175 - loss: 0.2413
Epoch 25/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9192 - loss: 0.2275
Epoch 26/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9217 - loss: 0.2116
Epoch 27/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9383 - loss: 0.2008
Epoch 28/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9292 - loss: 0.1984
Epoch 29/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9317 - loss: 0.1988
Epoch 30/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9458 - loss: 0.1762
Epoch 31/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9442 - loss: 0.1697
Epoch 32/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9467 - loss: 0.1709
Epoch 33/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9483 - loss: 0.1624
Epoch 34/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9525 - loss: 0.1405
Epoch 35/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9500 - loss: 0.1536
Epoch 36/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9483 - loss: 0.1466
Epoch 37/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9525 - loss: 0.1398
Epoch 38/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9642 - loss: 0.1239
Epoch 39/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9617 - loss: 0.1286
Epoch 40/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9650 - loss: 0.1175
Epoch 41/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9567 - loss: 0.1275
Epoch 42/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0935
Epoch 43/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9592 - loss: 0.1145
Epoch 44/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9700 - loss: 0.1037
Epoch 45/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9667 - loss: 0.1048
Epoch 46/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0946
Epoch 47/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9700 - loss: 0.1020
Epoch 48/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9708 - loss: 0.0943
Epoch 49/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9700 - loss: 0.0904
Epoch 50/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9700 - loss: 0.0918
Epoch 51/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9717 - loss: 0.0894
Epoch 52/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9792 - loss: 0.0808
Epoch 53/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9725 - loss: 0.0768
Epoch 54/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9725 - loss: 0.0829
Epoch 55/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9708 - loss: 0.0765
Epoch 56/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9792 - loss: 0.0694
Epoch 57/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9825 - loss: 0.0711
Epoch 58/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9758 - loss: 0.0730
Epoch 59/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9808 - loss: 0.0667
Epoch 60/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9750 - loss: 0.0730
Epoch 61/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9733 - loss: 0.0690
Epoch 62/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9833 - loss: 0.0616
Epoch 63/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9783 - loss: 0.0606
Epoch 64/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9783 - loss: 0.0651
Epoch 65/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9758 - loss: 0.0621
Epoch 66/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9775 - loss: 0.0694
Epoch 67/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9867 - loss: 0.0482
Epoch 68/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9900 - loss: 0.0410
Epoch 69/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9858 - loss: 0.0494
Epoch 70/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9883 - loss: 0.0464
Epoch 71/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9858 - loss: 0.0475
Epoch 72/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9833 - loss: 0.0492
Epoch 73/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9842 - loss: 0.0455
Epoch 74/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9800 - loss: 0.0482
Epoch 75/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9900 - loss: 0.0399
Epoch 76/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9908 - loss: 0.0369
Epoch 77/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9817 - loss: 0.0534
Epoch 78/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9908 - loss: 0.0355
Epoch 79/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9900 - loss: 0.0393
Epoch 80/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9850 - loss: 0.0425
Epoch 81/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9800 - loss: 0.0539
Epoch 82/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9850 - loss: 0.0437
Epoch 83/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9875 - loss: 0.0357
Epoch 84/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9900 - loss: 0.0351
Epoch 85/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9858 - loss: 0.0346
Epoch 86/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9958 - loss: 0.0270
Epoch 87/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9867 - loss: 0.0329
Epoch 88/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9908 - loss: 0.0328
Epoch 89/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9917 - loss: 0.0320
Epoch 90/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9925 - loss: 0.0296
Epoch 91/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9925 - loss: 0.0307
Epoch 92/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9883 - loss: 0.0380
Epoch 93/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9950 - loss: 0.0263
Epoch 94/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9933 - loss: 0.0235
Epoch 95/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9942 - loss: 0.0220
Epoch 96/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9908 - loss: 0.0279
Epoch 97/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9842 - loss: 0.0399
Epoch 98/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9933 - loss: 0.0257
Epoch 99/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9983 - loss: 0.0190
Epoch 100/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9958 - loss: 0.0182

In [749]:
def recomand(*features):
    input_data = np.array([features])
    scaled_input = sc.transform(input_data)

    pred = classifier.predict(scaled_input, verbose=0)

    pred_class_idx = np.argmax(pred)

    job_title = le_job.inverse_transform([pred_class_idx])[0]
    confidence = float(pred[0][pred_class_idx]) * 100

    return job_title, confidence

In [750]:
sample_job_title,sample_conf=recomand(2,	0,	3,	4,	0,	360000.0,	160000,	300000,	14,	13,	0,	0,	4,	1480,	9.1,	98,	42.7,	7.7,	2026,	1,	1,	1,	1,	0)

sample_job_title, sample_conf

C:\Users\vv\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

('LLM Engineer', 99.68777894973755)

In [751]:
sample_job_title,sample_conf=recomand(1498,	0,	1,	4,	1,	145000.0	,145000,	290000,	2,	6,	1,	1,	8,	631,	8.5,	91,	78.8,	7.4,	2025,	5,	1,	1,	0,	2)

sample_job_title, sample_conf

C:\Users\vv\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

('NLP Engineer', 99.99626874923706)

In [752]:
print(len(le_job.classes_))
print(classifier.output_shape)
print(np.unique(y))

25
(None, 25)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]