# DECISION_TREE_COVID_PREDICT

In [198]:
import pandas as pd

In [199]:
df=pd.read_csv(r"C:\Users\vv\OneDrive\Desktop\PYTHON\Covid Data.csv")
df

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [200]:
df.columns

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU'],
      dtype='object')

In [201]:
df.isnull().sum()

USMER                   0
MEDICAL_UNIT            0
SEX                     0
PATIENT_TYPE            0
DATE_DIED               0
INTUBED                 0
PNEUMONIA               0
AGE                     0
PREGNANT                0
DIABETES                0
COPD                    0
ASTHMA                  0
INMSUPR                 0
HIPERTENSION            0
OTHER_DISEASE           0
CARDIOVASCULAR          0
OBESITY                 0
RENAL_CHRONIC           0
TOBACCO                 0
CLASIFFICATION_FINAL    0
ICU                     0
dtype: int64

In [202]:
t=df.select_dtypes('int','float')
t

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,97,1,65,2,2,2,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,97,1,72,97,2,2,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,1,2,55,97,1,2,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,97,2,53,2,2,2,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,97,2,68,97,1,2,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,97,2,40,97,2,2,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,2,2,51,97,2,2,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,97,2,55,97,2,2,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,97,2,28,97,2,2,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,97,2,52,97,2,2,2,2,2,2,2,2,2,2,7,97

In [203]:
t.corr()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
USMER,1.000000,0.127927,-0.001126,-0.190570,0.175457,-0.154950,-0.045088,-0.001469,0.014704,0.011030,0.010814,0.003234,0.014830,-0.015763,0.010097,0.014567,0.011527,0.010638,0.028840,0.174901
MEDICAL_UNIT,0.127927,1.000000,0.001475,-0.205413,0.205243,-0.046433,-0.082223,0.005300,0.019523,0.014209,0.013312,0.011785,0.020964,0.027453,0.014406,0.019577,0.014751,0.012282,0.079981,0.205141
SEX,-0.001126,0.001475,1.000000,0.089505,-0.089943,-0.012131,0.028367,0.992713,0.008888,0.009372,0.010415,0.007999,0.009257,0.009039,0.008174,0.009858,0.008249,0.004919,-0.057782,-0.089844
PATIENT_TYPE,-0.190570,-0.205413,0.089505,1.000000,-0.976335,0.022966,0.315193,0.088340,0.008743,0.019548,0.023042,0.024924,0.006852,0.036724,0.022175,0.019650,0.018873,0.022123,-0.183370,-0.975810
INTUBED,0.175457,0.205243,-0.089943,-0.976335,1.000000,0.079743,-0.317945,-0.088097,-0.009215,-0.020124,-0.023446,-0.024140,-0.007628,-0.035404,-0.022442,-0.020217,-0.019309,-0.022428,0.193075,0.999434
PNEUMONIA,-0.154950,-0.046433,-0.012131,0.022966,0.079743,1.000000,-0.073127,-0.007284,-0.004484,-0.005618,-0.005392,-0.000802,-0.004799,0.001612,-0.004758,-0.004276,-0.005287,-0.004325,0.075351,0.079691
AGE,-0.045088,-0.082223,0.028367,0.315193,-0.317945,-0.073127,1.000000,0.027257,0.004422,0.019048,0.022715,0.022820,-0.004964,0.022837,0.019489,0.015500,0.020124,0.021263,-0.152637,-0.317813
PREGNANT,-0.001469,0.005300,0.992713,0.088340,-0.088097,-0.007284,0.027257,1.000000,0.014707,0.015736,0.016765,0.014265,0.015335,0.014175,0.014378,0.015895,0.014392,0.010794,-0.057809,-0.087991
DIABETES,0.014704,0.019523,0.008888,0.008743,-0.009215,-0.004484,0.004422,0.014707,1.000000,0.828823,0.829349,0.781108,0.835018,0.634611,0.809417,0.752739,0.812657,0.771763,-0.004739,-0.009223
COPD,0.011030,0.014209,0.009372,0.019548,-0.020124,-0.005618,0.019048,0.015736,0.828823,1.000000,0.908929,0.852273,0.855249,0.687323,0.880097,0.814868,0.884032,0.836097,-0.010336,-0.020146
ASTHMA,0.010814,0.013312,0.010415,0.023042,-0.023446,-0.005392,0.022715,0.016765,0.829349,0.908929,1.000000,0.868917,0.864264,0.696709,0.891026,0.824631,0.895050,0.845067,-0.011178,-0.023415
INMSUPR,0.003234,0.011785,0.007999,0.024924,-0.024140,-0.000802,0.022820,0.014265,0.781108,0.852273,0.868917,1.000000,0.825158,0.734826,0.853365,0.783953,0.852755,0.806749,-0.009412,-0.024077
HIPERTENSION,0.014830,0.020964,0.009257,0.006852,-0.007628,-0.004799,-0.004964,0.015335,0.835018,0.855249,0.864264,0.825158,1.000000,0.671532,0.861063,0.805127,0.860477,0.816539,-0.006020,-0.007573
OTHER_DISEASE,-0.015763,0.027453,0.009039,0.036724,-0.035404,0.001612,0.022837,0.014175,0.634611,0.687323,0.696709,0.734826,0.671532,1.000000,0.717129,0.649809,0.704725,0.668621,-0.011143,-0.035330
CARDIOVASCULAR,0.010097,0.014406,0.008174,0.022175,-0.022442,-0.004758,0.019489,0.014378,0.809417,0.880097,0.891026,0.853365,0.861063,0.717129,1.000000,0.834389,0.913248,0.858102,-0.012143,-0.022413
OBESITY,0.014567,0.019577,0.009858,0.019650,-0.020217,-0.004276,0.015500,0.015895,0.752739,0.814868,0.824631,0.783953,0.805127,0.649809,0.834389,1.000000,0.842466,0.801834,-0.006924,-0.020254
RENAL_CHRONIC,0.011527,0.014751,0.008249,0.018873,-0.019309,-0.005287,0.020124,0.014392,0.812657,0.884032,0.895050,0.852755,0.860477,0.704725,0.913248,0.842466,1.000000,0.868761,-0.011342,-0.019285
TOBACCO,0.010638,0.012282,0.004919,0.022123,-0.022428,-0.004325,0.021263,0.010794,0.771763,0.836097,0.845067,0.806749,0.816539,0.668621,0.858102,0.801834,0.868761,1.000000,-0.012567,-0.022445
CLASIFFICATION_FINAL,0.028840,0.079981,-0.057782,-0.183370,0.193075,0.075351,-0.152637,-0.057809,-0.004739,-0.010336,-0.011178,-0.009412,-0.006020,-0.011143,-0.012143,-0.006924,-0.011342,-0.012567,1.000000,0.193163
ICU,0.174901,0.205141,-0.089844,-0.975810,0.999434,0.079691,-0.317813,-0.087991,-0.009223,-0.020146,-0.023415,-0.024077,-0.007573,-0.035330,-0.022413,-0.020254,-0.019285,-0.022445,0.193163,1.000000

In [204]:
x = t[['USMER','INTUBED','COPD','ASTHMA','INMSUPR','HIPERTENSION','CARDIOVASCULAR','TOBACCO','ICU']]
x

,USMER,INTUBED,COPD,ASTHMA,INMSUPR,HIPERTENSION,CARDIOVASCULAR,TOBACCO,ICU
0,2,97,2,2,2,1,2,2,97
1,2,97,2,2,2,1,2,2,97
2,2,1,2,2,2,2,2,2,2
3,2,97,2,2,2,2,2,2,97
4,2,97,2,2,2,1,2,2,97
...,...,...,...,...,...,...,...,...,...
1048570,2,97,2,2,2,2,2,2,97
1048571,1,2,2,2,2,1,2,2,2
1048572,2,97,2,2,2,2,2,2,97
1048573,2,97,2,2,2,2,2,2,97
1048574,2,97,2,2,2,2,2,2,97

In [205]:
# classification: covid test findings. Values 1-3 mean that the patient was diagnosed with covid in different
# degrees. 4 or higher means that the patient is not a carrier of covid or that the test is inconclusive.
y=t.iloc[:,-2]
y

0          3
1          5
2          3
3          7
4          3
          ..
1048570    7
1048571    7
1048572    7
1048573    7
1048574    7
Name: CLASIFFICATION_FINAL, Length: 1048575, dtype: int64

In [206]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=1000)

In [207]:
from sklearn.tree import DecisionTreeClassifier

cls=DecisionTreeClassifier(criterion= 'entropy', random_state=1000)
cls.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=1000)

In [208]:
y_pred=cls.predict(x_test)
y_pred

array([7, 7, 7, ..., 7, 7, 7], shape=(314573,))

In [209]:
y_test

913103    7
651182    3
169298    6
300303    7
215709    6
         ..
552101    3
319039    7
973895    7
395541    3
604607    3
Name: CLASIFFICATION_FINAL, Length: 314573, dtype: int64

In [210]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

results=confusion_matrix(y_test,y_pred)
print('confusion matrix')
print(results)
print('Accuracy score:', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

confusion matrix
[[     3      1    624      0      0      3   1908]
 [     0      0    437      0      0      1     70]
 [    10      5  31085      0      9     24  83483]
 [     0      0    185      0      0      0    751]
 [     0      0   1427      0      2      3   6261]
 [     6      5   4951      0      2     24  33747]
 [     6      6  16646      0      8     35 132845]]
Accuracy score: 0.5212112927682923
              precision    recall  f1-score   support

           1       0.12      0.00      0.00      2539
           2       0.00      0.00      0.00       508
           3       0.56      0.27      0.37    114616
           4       0.00      0.00      0.00       936
           5       0.10      0.00      0.00      7693
           6       0.27      0.00      0.00     38735
           7       0.51      0.89      0.65    149546

    accuracy                           0.52    314573
   macro avg       0.22      0.17      0.15    314573
weighted avg       0.48      0.52      0.44    314573

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [213]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

cls=RandomForestClassifier(n_estimators=300,criterion= 'entropy', random_state=42)
cls.fit(x_train,y_train)

In [ ]:
y_pred=cls.predict(x_test)
y_pred

In [ ]:
y_test