# PCA_MULTI_DISEASES

In [139]:
import pandas as pd

In [140]:
df=pd.read_csv(r"C:\Users\vv\OneDrive\Desktop\PYTHON\Unsupervised\GeneX_3000_Synthetic_Genomic_Dataset.csv")
df

,Patient_ID,Age,Gender,Family_History,Gene_0001,Gene_0002,Gene_0003,Gene_0004,Gene_0005,Gene_0006,...,Gene_2995,Gene_2996,Gene_2997,Gene_2998,Gene_2999,Gene_3000,Disease_Label,Severity_Score,Survival_Probability,Treatment_Response
0,1,55,Male,0,1.023404,-0.139947,-0.413790,0.758524,-0.933113,0.205634,...,-0.636061,-0.140668,-0.365725,1.027790,-2.590153,-0.178376,Healthy,0.26,0.9900,0
1,2,48,Female,0,-0.295163,-0.006925,-0.442832,0.833048,-0.209680,0.108168,...,-2.257270,-1.909278,-2.220490,1.540117,0.614155,0.755975,Cancer_A,27.85,0.7657,1
2,3,57,Female,0,0.798492,-0.468213,1.873799,0.272942,-0.059209,0.903118,...,1.955905,-0.000073,-1.091311,-2.488657,-0.938276,0.377351,Cancer_A,25.83,0.7966,1
3,4,68,Male,0,0.514915,-0.492404,-0.349961,0.056901,0.309218,0.829957,...,-0.216898,1.185594,0.328102,0.702021,-0.994854,0.161378,Cancer_B,43.88,0.7144,0
4,5,47,Male,1,1.523395,1.202082,0.655207,0.773802,1.979540,0.639314,...,0.720966,-0.816354,0.257021,-0.211293,0.443550,0.523168,Autoimmune,58.60,0.4904,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,39,Female,1,-0.447195,0.523523,1.044762,1.408241,-0.499448,0.836782,...,-0.655359,0.003642,-0.144189,-1.608613,1.103356,0.283554,Cancer_A,28.96,0.7509,0
14996,14997,64,Female,0,-0.745678,0.404878,0.127673,0.159905,-1.429051,-0.193381,...,1.467687,-0.313000,-1.214831,1.344130,-0.046887,0.235518,Cancer_A,18.18,0.8598,1
14997,14998,65,Female,0,-0.222254,-0.381910,-0.021404,0.280609,-0.425509,-0.948008,...,0.091039,0.340632,-1.596310,-2.152402,0.714869,-0.892511,Autoimmune,69.74,0.4305,0
14998,14999,39,Male,0,0.405340,0.830560,-1.657677,-0.696589,-0.702894,-0.051393,...,0.496693,-0.035710,-0.004041,-0.001033,1.155131,0.622247,Autoimmune,60.89,0.4406,0
14999,15000,48,Female,0,0.479192,-0.755044,-0.300962,1.310565,-0.079109,0.965069,...,-0.369455,0.144906,-0.058036,0.321981,-0.461731,0.834879,Cancer_A,22.72,0.8666,0

In [141]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Family_History', 'Gene_0001',
       'Gene_0002', 'Gene_0003', 'Gene_0004', 'Gene_0005', 'Gene_0006',
       ...
       'Gene_2995', 'Gene_2996', 'Gene_2997', 'Gene_2998', 'Gene_2999',
       'Gene_3000', 'Disease_Label', 'Severity_Score', 'Survival_Probability',
       'Treatment_Response'],
      dtype='object', length=3008)

In [142]:
from sklearn.preprocessing import LabelEncoder



label_encoders = {}
categorical_columns = ['Gender','Disease_Label']	

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [143]:
df

,Patient_ID,Age,Gender,Family_History,Gene_0001,Gene_0002,Gene_0003,Gene_0004,Gene_0005,Gene_0006,...,Gene_2995,Gene_2996,Gene_2997,Gene_2998,Gene_2999,Gene_3000,Disease_Label,Severity_Score,Survival_Probability,Treatment_Response
0,1,55,1,0,1.023404,-0.139947,-0.413790,0.758524,-0.933113,0.205634,...,-0.636061,-0.140668,-0.365725,1.027790,-2.590153,-0.178376,3,0.26,0.9900,0
1,2,48,0,0,-0.295163,-0.006925,-0.442832,0.833048,-0.209680,0.108168,...,-2.257270,-1.909278,-2.220490,1.540117,0.614155,0.755975,1,27.85,0.7657,1
2,3,57,0,0,0.798492,-0.468213,1.873799,0.272942,-0.059209,0.903118,...,1.955905,-0.000073,-1.091311,-2.488657,-0.938276,0.377351,1,25.83,0.7966,1
3,4,68,1,0,0.514915,-0.492404,-0.349961,0.056901,0.309218,0.829957,...,-0.216898,1.185594,0.328102,0.702021,-0.994854,0.161378,2,43.88,0.7144,0
4,5,47,1,1,1.523395,1.202082,0.655207,0.773802,1.979540,0.639314,...,0.720966,-0.816354,0.257021,-0.211293,0.443550,0.523168,0,58.60,0.4904,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,39,0,1,-0.447195,0.523523,1.044762,1.408241,-0.499448,0.836782,...,-0.655359,0.003642,-0.144189,-1.608613,1.103356,0.283554,1,28.96,0.7509,0
14996,14997,64,0,0,-0.745678,0.404878,0.127673,0.159905,-1.429051,-0.193381,...,1.467687,-0.313000,-1.214831,1.344130,-0.046887,0.235518,1,18.18,0.8598,1
14997,14998,65,0,0,-0.222254,-0.381910,-0.021404,0.280609,-0.425509,-0.948008,...,0.091039,0.340632,-1.596310,-2.152402,0.714869,-0.892511,0,69.74,0.4305,0
14998,14999,39,1,0,0.405340,0.830560,-1.657677,-0.696589,-0.702894,-0.051393,...,0.496693,-0.035710,-0.004041,-0.001033,1.155131,0.622247,0,60.89,0.4406,0
14999,15000,48,0,0,0.479192,-0.755044,-0.300962,1.310565,-0.079109,0.965069,...,-0.369455,0.144906,-0.058036,0.321981,-0.461731,0.834879,1,22.72,0.8666,0

In [144]:
x=df.iloc[:, 1:801].values
x.shape

(15000, 800)

In [145]:
y=df.iloc[:,3004].values
y

array([3, 1, 1, ..., 0, 0, 1])

In [146]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

x_train.shape

(12000, 800)

In [147]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [148]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [149]:
pred=knn.predict(x_test)
pred

array([1, 1, 3, ..., 3, 3, 1])

In [150]:
from sklearn.metrics import accuracy_score

In [151]:
accuracy_score(y_test, pred)

0.793

In [152]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

results=confusion_matrix(y_test, pred)
print('confusion_matrix')
print(results)
print('Accuracy Score:', accuracy_score(y_test, pred))

confusion_matrix
[[ 68   0   0 410]
 [  0 718   0   0]
 [  0   0 594   0]
 [211   0   0 999]]
Accuracy Score: 0.793

In [153]:
from sklearn.preprocessing  import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test-sc.transform(x_test)

array([[ 4.44679774e+01,  1.02190656e+00,  6.40265630e-01, ...,
        -9.97266115e-03,  2.49356593e-02, -2.47695710e-03],
       [ 5.63800309e+01,  1.02190656e+00, -5.61851757e-01, ...,
        -1.22199415e-02,  2.08463844e-02, -9.51153762e-04],
       [ 3.07233004e+01,  2.14369492e-02,  6.40265630e-01, ...,
        -1.00531100e-02,  1.46552522e-02, -7.03047924e-03],
       ...,
       [ 4.99658482e+01,  1.02190656e+00,  6.40265630e-01, ...,
        -9.16197193e-03,  1.66165060e-02, -4.65731580e-03],
       [ 5.08821600e+01,  2.14369492e-02,  6.40265630e-01, ...,
        -8.68535979e-03,  1.62323177e-02,  1.24002877e-03],
       [ 4.26353538e+01,  1.02190656e+00,  6.40265630e-01, ...,
        -1.14283818e-02,  2.53471149e-02, -2.56471722e-03]])

In [154]:
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
x_train_new=pca.fit_transform(x_train)
x_test_new=pca.transform(x_test)

In [155]:
print(x_train.shape)

(12000, 800)

In [156]:
print(x_train_new.shape)

(12000, 10)

In [157]:
pca.explained_variance_ratio_

array([0.11928162, 0.06430193, 0.00184098, 0.00182506, 0.00181412,
       0.00180865, 0.00179909, 0.00179182, 0.00178976, 0.00178491])

In [158]:
knn.fit(x_train_new, y_train)

KNeighborsClassifier()

In [159]:
pred_new=knn.predict(x_test_new)
pred_new

array([1, 1, 3, ..., 3, 3, 1])

In [160]:
accuracy_score(y_test, pred_new)

0.7976666666666666